apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-connection-details
  namespace: luckydraw
data:
  REDIS_HOST: redis.luckydraw.svc
  REDIS_PORT: "6379"
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: luckydraw
type: Opaque
data:
  POSTGRES_PASSWORD: cG9zdGdyZXM= # encode value for postgres
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-connection-details
  namespace: luckydraw
data:
  POSTGRES_HOST: postgres.luckydraw.svc
  POSTGRES_PORT: "5432"
  POSTGRES_USER: postgres
  POSTGRES_DB: postgres
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pickwinner-config
  namespace: luckydraw
data:
  ADMIN_USERNAME: admin
  ADMIN_PASSWORD: admin