apiVersion: apps/v1
kind: Deployment
metadata:
  name: sync-redis-to-postgres
  namespace: luckydraw
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sync-redis-to-postgres
  template:
    metadata:
      labels:
        app: sync-redis-to-postgres
    spec:
      containers:
      - name: sync-redis-to-postgres
        image: ghcr.io/kul-samples/thinknyx-redis-to-postgres-worker-app:latest
        resources:
          limits:
            memory: "150Mi"
            cpu: "150m"
          requests:
            memory: "100Mi"
            cpu: "100m"
        envFrom:
        - configMapRef:
            name: redis-connection-details
        - configMapRef:
            name: postgres-connection-details
        - secretRef:
            name: postgres-credentials
        env:
        - name: REDIS_POLL_INTERVAL
          value: "5" # Poll Redis every 5 seconds